//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14Sept2019SirTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_City
    {
        public int cityid { get; set; }
        public string cityname { get; set; }
        public Nullable<int> FKstateid { get; set; }
    
        public virtual tbl_State tbl_State { get; set; }
    }
}
